spring.application.name=clinica-dental

# H2 Database Configuration (Base de datos en memoria para desarrollo)
spring.datasource.url=jdbc:h2:mem:clinica_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (opcional - para ver la BD en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


# JWT Configuration
app.jwt.secret=ClinicaDentalSecretKey2026MuySeguraParaGenerarTokensJWTDe256Bits
app.jwt.expiration=86400000