# ===============================
#   CONFIGURACIÓN GENERAL
# ===============================
spring.application.name=clinica-dental
server.port=8080
# Deshabilita JMX para evitar conflictos de arranque en local
spring.jmx.enabled=false

# ===============================
#   CONFIGURACIÓN BASE DE DATOS (DOCKER)
# ===============================
# Se cambió de 127.0.0.1 a localhost por estándar de Docker Desktop
# Se añadió allowPublicKeyRetrieval=true para corregir el error de DBeaver
# Se activó createDatabaseIfNotExist=true para que Spring cree la DB 'db_clinica' automáticamente
spring.datasource.url=jdbc:mysql://localhost:3306/db_clinica?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root

spring.datasource.password=mario123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
#   JPA / HIBERNATE
# ===============================
# 'update' creará las tablas de tu sistema dental automáticamente al iniciar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Logs de SQL para que veas las consultas en la consola de IntelliJ/Eclipse
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================================================
# CONFIGURACIÓN DE SEGURIDAD JWT (CLÍNICA DENTAL)
# ==============================================================
# Se mantiene tu clave secreta y tiempo de expiración de 24h
app.jwt.secret=EstaEsUnaClaveSecretaSuperLargaYSeguraParaLaClinicaDental2026
app.jwt.expiration=86400000